-- Run as ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS COST_ANALYZER_ROLE;
CREATE DATABASE IF NOT EXISTS COST_ANALYZER_DB;
CREATE SCHEMA IF NOT EXISTS COST_ANALYZER_DB.COST_ANALYZER_SCHEMA;
CREATE WAREHOUSE IF NOT EXISTS COST_ANALYZER_WH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

-- Create the stage that will hold the Streamlit app source files
CREATE STAGE IF NOT EXISTS COST_ANALYZER_DB.COST_ANALYZER_SCHEMA.APP_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    COMMENT = 'Source code stage for Cost Analyzer Streamlit app';

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE COST_ANALYZER_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE COST_ANALYZER_ROLE;

-- Register the Streamlit app pointing at the stage
CREATE OR REPLACE STREAMLIT COST_ANALYZER_DB.COST_ANALYZER_SCHEMA.COST_ANALYZER_APP
    FROM '@COST_ANALYZER_DB.COST_ANALYZER_SCHEMA.APP_STAGE'
    MAIN_FILE = '/streamlit_app.py';

GRANT READ, WRITE ON STAGE COST_ANALYZER_DB.COST_ANALYZER_SCHEMA.APP_STAGE TO ROLE COST_ANALYZER_ROLE;
GRANT USAGE ON STREAMLIT COST_ANALYZER_DB.COST_ANALYZER_SCHEMA.COST_ANALYZER_APP TO ROLE COST_ANALYZER_ROLE;

