-- Run as ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS COST_ANALYZER_ROLE;
CREATE DATABASE IF NOT EXISTS COST_ANALYZER_DB;
CREATE SCHEMA IF NOT EXISTS COST_ANALYZER_DB.COST_ANALYZER_SCHEMA;
CREATE WAREHOUSE IF NOT EXISTS COST_ANALYZER_WH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE COST_ANALYZER_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE COST_ANALYZER_ROLE;
CREATE OR REPLACE STREAMLIT COST_ANALYZER_DB.COST_ANALYZER_SCHEMA.COST_ANALYZER_APP FROM '/' MAIN_FILE = '/streamlit_app.py';
GRANT USAGE ON STREAMLIT COST_ANALYZER_DB.COST_ANALYZER_SCHEMA.COST_ANALYZER_APP TO ROLE COST_ANALYZER_ROLE;
